// Mock EV Charger data for Singapore
// In a real application, this would come from an API

export interface EvCharger {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  provider: string; // e.g., "Shell Recharge", "SP Group", "BlueSG"
  powerKw: number; // Charging power in kW
  connectorType: string; // e.g., "Type 2", "CCS", "CHAdeMO"
  numberOfPorts: number;
  availability?: 'available' | 'occupied' | 'unknown';
  pricePerKwh?: number; // Price in SGD per kWh
  operatingHours?: string;
}

// Sample EV chargers across Singapore
export const evChargers: EvCharger[] = [
  {
    id: 'ev-1',
    name: 'Shell Recharge @ Orchard',
    address: '238 Orchard Road, Singapore 238855',
    latitude: 1.3016,
    longitude: 103.8367,
    provider: 'Shell Recharge',
    powerKw: 50,
    connectorType: 'CCS / CHAdeMO',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.60,
    operatingHours: '24/7',
  },
  {
    id: 'ev-2',
    name: 'SP Charging @ Marina Bay Sands',
    address: '10 Bayfront Avenue, Singapore 018956',
    latitude: 1.2838,
    longitude: 103.8607,
    provider: 'SP Group',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 4,
    availability: 'available',
    pricePerKwh: 0.50,
    operatingHours: '24/7',
  },
  {
    id: 'ev-3',
    name: 'BlueSG @ Chinatown Point',
    address: '133 New Bridge Road, Singapore 059413',
    latitude: 1.2857,
    longitude: 103.8445,
    provider: 'BlueSG',
    powerKw: 7,
    connectorType: 'Type 2',
    numberOfPorts: 3,
    availability: 'occupied',
    pricePerKwh: 0.45,
    operatingHours: '24/7',
  },
  {
    id: 'ev-4',
    name: 'Charge+ @ Sentosa',
    address: '8 Sentosa Gateway, Singapore 098269',
    latitude: 1.2577,
    longitude: 103.8229,
    provider: 'Charge+',
    powerKw: 50,
    connectorType: 'CCS',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.65,
    operatingHours: '6:00 AM - 11:00 PM',
  },
  {
    id: 'ev-5',
    name: 'SP Charging @ Raffles Place',
    address: '6 Raffles Quay, Singapore 048580',
    latitude: 1.2819,
    longitude: 103.8519,
    provider: 'SP Group',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 3,
    availability: 'available',
    pricePerKwh: 0.50,
    operatingHours: '24/7',
  },
  {
    id: 'ev-6',
    name: 'Shell Recharge @ Jurong East',
    address: '50 Jurong Gateway Road, Singapore 608549',
    latitude: 1.3336,
    longitude: 103.7423,
    provider: 'Shell Recharge',
    powerKw: 50,
    connectorType: 'CCS / CHAdeMO',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.60,
    operatingHours: '24/7',
  },
  {
    id: 'ev-7',
    name: 'Charge+ @ Tampines Mall',
    address: '4 Tampines Central 5, Singapore 529510',
    latitude: 1.3526,
    longitude: 103.9443,
    provider: 'Charge+',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 4,
    availability: 'available',
    pricePerKwh: 0.55,
    operatingHours: '8:00 AM - 10:00 PM',
  },
  {
    id: 'ev-8',
    name: 'SP Charging @ Woodlands',
    address: '30 Woodlands Avenue 2, Singapore 738343',
    latitude: 1.4355,
    longitude: 103.7865,
    provider: 'SP Group',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 3,
    availability: 'unknown',
    pricePerKwh: 0.50,
    operatingHours: '24/7',
  },
  {
    id: 'ev-9',
    name: 'BlueSG @ Bukit Timah',
    address: '144 Upper Bukit Timah Road, Singapore 588177',
    latitude: 1.3429,
    longitude: 103.7759,
    provider: 'BlueSG',
    powerKw: 7,
    connectorType: 'Type 2',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.45,
    operatingHours: '24/7',
  },
  {
    id: 'ev-10',
    name: 'Shell Recharge @ Changi Airport',
    address: '60 Airport Boulevard, Singapore 819643',
    latitude: 1.3644,
    longitude: 103.9915,
    provider: 'Shell Recharge',
    powerKw: 50,
    connectorType: 'CCS / CHAdeMO',
    numberOfPorts: 4,
    availability: 'available',
    pricePerKwh: 0.60,
    operatingHours: '24/7',
  },
  {
    id: 'ev-11',
    name: 'Charge+ @ Vivocity',
    address: '1 HarbourFront Walk, Singapore 098585',
    latitude: 1.2644,
    longitude: 103.8222,
    provider: 'Charge+',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 3,
    availability: 'occupied',
    pricePerKwh: 0.55,
    operatingHours: '8:00 AM - 11:00 PM',
  },
  {
    id: 'ev-12',
    name: 'SP Charging @ NUS',
    address: '21 Lower Kent Ridge Road, Singapore 119077',
    latitude: 1.2966,
    longitude: 103.7764,
    provider: 'SP Group',
    powerKw: 22,
    connectorType: 'Type 2',
    numberOfPorts: 4,
    availability: 'available',
    pricePerKwh: 0.50,
    operatingHours: '24/7',
  },
  {
    id: 'ev-13',
    name: 'BlueSG @ Bugis Junction',
    address: '200 Victoria Street, Singapore 188021',
    latitude: 1.2990,
    longitude: 103.8555,
    provider: 'BlueSG',
    powerKw: 7,
    connectorType: 'Type 2',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.45,
    operatingHours: '24/7',
  },
  {
    id: 'ev-14',
    name: 'Charge+ @ Suntec City',
    address: '3 Temasek Boulevard, Singapore 038983',
    latitude: 1.2953,
    longitude: 103.8583,
    provider: 'Charge+',
    powerKw: 50,
    connectorType: 'CCS',
    numberOfPorts: 3,
    availability: 'available',
    pricePerKwh: 0.65,
    operatingHours: '24/7',
  },
  {
    id: 'ev-15',
    name: 'Shell Recharge @ Paya Lebar',
    address: '60 Paya Lebar Road, Singapore 409051',
    latitude: 1.3182,
    longitude: 103.8928,
    provider: 'Shell Recharge',
    powerKw: 50,
    connectorType: 'CCS / CHAdeMO',
    numberOfPorts: 2,
    availability: 'available',
    pricePerKwh: 0.60,
    operatingHours: '24/7',
  },
];
